Feature prewarm
awslabs/aws-cloudfront-extensions pull request #334
Opened 2023-03-08 02:59 UTC by o0OooO

*Issue #, if available:*

*Description of changes:*
add Chinese region to pre-warm，add a new type to pre-warm by country

*How Has This Been Tested:*
unit test，according to changing the behavior and invalidation in CloudFront to test if pre-warm is available

*[x] My testing has passed*

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-03-08 03:02 UTC, NingLu commented on edge/cdk/extensions/prewarm/lambda/agent/agent.py
> +    if len(node_list) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0` or `if len(val) &gt; 0`

 [Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-03-08 03:18 UTC, guming3d commented on docs-ig/en/api-reference-guide/extension-repository.md
> +        * china： China
Better to add comment to let user know that China Pop prewarm can only used by deploying this solution in China regions, otherwise it will always fail.

2023-03-08 03:20 UTC, guming3d commented on edge/cdk/extensions/prewarm/README-cn.md
> +      * china： China
same comment with README.md, China pop prewarm can only be triggered from Solution deployed in China region.

2023-03-08 03:21 UTC, guming3d commented on edge/cdk/extensions/prewarm/README-cn.md
> +    "region": ["ATL56-C1", "DFW55-C3"]|"all"|["apac","au","ca","sa","eu","jp","us"]|["china","india"] // "all" to prewarm all pop node
better to list all supported Country code in this doc.

2023-03-08 05:07 UTC, guming3d commented on edge/cdk/extensions/prewarm/lambda/scheduler/scheduler.py
> +        if pop_region != ALL:
I am not quit understand this logic, if pop_region is not 'all', we should raise the error?

2023-03-08 05:08 UTC, guming3d commented on edge/cdk/extensions/prewarm/lambda/scheduler/scheduler.py
> +    # if type(pop_region) == str:
Please remove unused code here.

2023-03-08 05:10 UTC, guming3d commented on edge/cdk/extensions/prewarm/lambda/scheduler/scheduler.py
> +    region_type = event_body['region_type']
The logic is not clear to me, we should check region type before checking the pop_region right? Please adding some comment here.

2023-03-08 05:11 UTC, guming3d requested changes
Please help to clarify the comment I addressed.

2023-03-08 09:15 UTC, rrxie commented on docs-ig/en/api-reference-guide/extension-repository.md
> +      * pop：pre-warm in PoP，the value of region field is a list of PoP
1. PoP stands for? We need to give the full name. 
2. pre-warm by pop? pre-warm by country? pre-warm by region?

2023-03-08 09:15 UTC, rrxie commented on docs-ig/en/api-reference-guide/extension-repository.md
> +      * region_type = "region": accept "all" or a region list, pre-warm in all regions or a specific region，eg:"all"|["apac", "au"], the available regions are：
Replace e.g with "for example"

2023-03-08 09:15 UTC, rrxie commented on docs-ig/en/api-reference-guide/extension-repository.md
> +      * region_type = "country": accept "all" or a country list: pre-warm in all countries or a specific country，eg:"all"|["india", "new_zealand"], the available countries are：
the available countries: -> the supported values are: ?

2023-03-09 03:26 UTC, o0OooO commented on edge/cdk/extensions/prewarm/lambda/scheduler/scheduler.py
> +        if pop_region != ALL:
pop_region can only accept one value of String type,and it is "all"
if the pop_region is "all",we should change the pop_region values named "all" to real pop list by region_type
I have commit this comment to this code block

2023-03-09 03:41 UTC, o0OooO commented on edge/cdk/extensions/prewarm/lambda/agent/agent.py
> +                        for i in failure_pre_map:
we change the status because of we can know if the file is processed successfully directly through the pop's iata successful and fail list

2023-03-09 03:42 UTC, o0OooO commented on edge/cdk/extensions/prewarm/lambda/agent/agent.py
> +                        for i in failure_pre_map:
it should be success if the iate exist one in the success list

2023-03-10 03:50 UTC, alvindaiyan commented
pipeline code has been merged, you guys need rebase or merge those code into your pr so that it can trigger the github action

2023-03-13 06:48 UTC, NingLu commented on edge/cdk/extensions/prewarm/lambda/agent/agent.py
> +                sqs.delete_message_batch(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This code makes a call to a batch operation, but it does not handle any errors returned by that batch operation. Batch operations can succeed without throwing exceptions even if some items in the request fail. Consider checking the return value of the batch operation for failures.

[Learn More](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs.html#SQS.Client.delete_message_batch)

2023-03-13 06:55 UTC, o0OooO commented
AGREE

2023-03-13 06:55 UTC, o0OooO commented
1

2023-03-13 06:57 UTC, o0OooO commented
AGREE

2023-03-13 06:58 UTC, o0OooO commented
1

2023-03-13 06:58 UTC, merged